name: Daily Evaluate (Telegram)

on:
  schedule:
    - cron: "15 9 * * *"   # 09:15 UTC (adapter après ton predict)
  workflow_dispatch: {}

jobs:
  eval:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install requests

      - name: Run evaluation & send Telegram
        env:
          EXCHANGE: ${{ secrets.EXCHANGE }}
          USE_TESTNET: ${{ secrets.USE_TESTNET }}
          SYMBOLS: ${{ secrets.SYMBOLS }}
          TIMEFRAME: ${{ secrets.TIMEFRAME }}
          LIMIT: ${{ secrets.LIMIT }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python -m src.evaluate
